# Generated by Django 3.2.7 on 2021-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_id', models.CharField(max_length=72, unique=True)),
                ('voting_account', models.CharField(max_length=56)),
                ('market_key', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=7, max_digits=20)),
                ('locked_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
