# Generated by Django 3.2.7 on 2021-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(max_length=56)),
                ('rank', models.PositiveIntegerField()),
                ('votes_value', models.DecimalField(decimal_places=7, max_digits=20)),
                ('voting_amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
