# Generated by Django 3.2.7 on 2021-10-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0001_initial'),
        ('voting', '0002_votingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsnapshot',
            name='market_key_object',
            field=models.ForeignObject(from_fields=('market_key',), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketkeys.marketkey', to_fields=('account_id',)),
        ),
    ]
