# Generated by Django 3.2.9 on 2021-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20211215_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingsnapshot',
            name='market_key',
            field=models.CharField(db_index=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='votingsnapshot',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
