# Generated by Django 3.2.9 on 2022-02-15 14:29

from django.db import migrations, models


def set_adjusted_value(apps, schema_editor):
    VotingSnapshot = apps.get_model('voting', 'VotingSnapshot')
    VotingSnapshot.objects.update(adjusted_votes_value=models.F('votes_value'))


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20211230_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsnapshot',
            name='adjusted_votes_value',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
        migrations.RunPython(
            set_adjusted_value,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='votingsnapshot',
            name='adjusted_votes_value',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
