# Generated by Django 3.2.13 on 2022-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_vote_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsnapshot',
            name='extra',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
