# Generated by Django 3.2.17 on 2023-04-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_votingsnapshot_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSnapshotAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=69)),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Up'), (2, 'Down')])),
                ('votes_sum', models.DecimalField(decimal_places=7, max_digits=20)),
                ('votes_count', models.PositiveIntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='voting.votingsnapshot')),
            ],
        ),
    ]
